######################
## Storage Component
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./storage
  prune: true
  wait: true

######################
## Cert Component
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: storage
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./certs
  prune: true
  wait: true
  healthChecks:
    - kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
    - kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager